테스트 코드에서 Fixture Monkey를 사용하기 어려운 이유
sirloin-dev/meatplatform-sandbox pull request #9
Opened 2022-03-25 07:08 UTC by yoonho92

2022-03-25 13:52 UTC, FrancescoJo commented on server/README.adoc
> +== 테스트코드에서 Fixture Monkey를 사용하기 어려운 이유
문구 수정해 주시는게 좋겠습니다.

"Kotlin 기반 프로젝트와, 테스트 코드에서..." 가 좀 더 맞는 표현 아닐까요?

Java 테스트 코드에서도 Fixture Monkey 를 사용하기 어려울까요?

2022-03-25 13:53 UTC, FrancescoJo commented on server/README.adoc
> +== 테스트코드에서 Fixture Monkey를 사용하기 어려운 이유
그리고, Fixture Monkey 나 AutoParams 같은 좋은 라이브러리를 왜 못 쓰고, 굳이 `Faker` 를 써서 하나하나 직접 구현할 수 밖에 없는지, 그 이유도 여기에 간단하게 한 문단으로 적어주시면 좋겠습니다.

2022-03-25 13:54 UTC, FrancescoJo commented on server/README.adoc
> +
위와 같은 구현에서  Fixture Monkey 를 적용하려면 어떤 오류가 발생하는지도 추가해 주세요.

2022-03-25 13:54 UTC, FrancescoJo commented on server/README.adoc
> +        internal data class Model(
이거 Indent 를 0으로 줄여도 될 것 같습니다.

2022-03-25 13:54 UTC, FrancescoJo commented on server/README.adoc
> +        ) : Editor
Editor 라는 타입이 소스코드에 없다면, 빼 주세요.

2022-03-25 13:55 UTC, FrancescoJo commented on server/README.adoc
> +[source, shell script]
source code type 수정해주세요.

2022-03-25 13:56 UTC, FrancescoJo commented on server/README.adoc
> +Fixture Monkey는 data class를 이용해 mock data를 생성하는데 class에 private 같은 접근지정자가 있으면 Fixture Monkey에서 접근이 되지 않아 문제가 생길 수 있다.
> Fixture Monkey는 data class를 이용해

확실한가요? Fixture Monkey 는 Java 기반 라이브러리 아닌가요?

2022-03-25 13:57 UTC, FrancescoJo commented on server/README.adoc
> +public final class MockUser {
좋습니다. 잘 설명해 주셨어요.

2022-03-25 13:58 UTC, FrancescoJo commented on server/README.adoc
> +=== 4. 데이터 오브젝트가 생성자를 통해 만드는 방식으로 제한된다.
아마, 데이터 오브젝트가 아니라, *생성자 파라미터를 가진 클래스* 로 제한될 것 같습니다.

```
class MockUser(
  var nickname: String = ""
  var profileImageUrl: String = ""
)
```

케이스에서는 Fixture Monkey 를 쓸 수있을 것 같은데, 확인해보시죠.

2022-03-25 13:59 UTC, FrancescoJo commented on server/README.adoc
> +=== 4. 데이터 오브젝트가 생성자를 통해 만드는 방식으로 제한된다.
는 https://github.com/sirloin-dev/meatplatform-sandbox/pull/9/files#diff-d94b46ab0ba876717d05fbeef005e7b515659a2cef9cb67cea6115d7da35ee03R500 여기에 이미 적어주셨네요.

제목만 수정해 주시면 되겠습니다.

2022-03-25 14:00 UTC, FrancescoJo requested changes
코멘트 확인 부탁합니다.

2022-03-26 06:35 UTC, yoonho92 commented
> 코멘트 확인 부탁합니다.

확인했습니다.
수정후 Re-request review 요청 드리겠습니다!

2022-03-28 01:56 UTC, FrancescoJo commented on server/README.adoc
> +코틀린에서는 자바에서는 없는 internal 접근제어자나 자바와는 다른 데이터 오브젝트의 생성 방식등으로 데이터 오브젝트에 접근 혹은 생성이 어렵기 때문에 코틀린 프로젝트에서는
요거 `internal` 키워드 코드 처리 해주시면 좀더 좋을 것 같습니다.

2022-03-28 01:57 UTC, FrancescoJo commented on server/README.adoc
> +=== 1. mock data를 만들기 위해 data class에 접근할 수 있어야하는데 internal일 경우 접근이 어렵다.
여기도 `data class` 나 `internal` 은 코드 처리 해 주시면 좋을 것 같아요.

2022-03-28 02:01 UTC, FrancescoJo requested changes
마지막으로 코멘트한 부분만 한번 더 손봐 주시면 좋겠습니다.

2022-03-28 02:01 UTC, FrancescoJo commented on server/README.adoc
> +        override val uuid: UUID,
예제 코드 indent 수정 필요 (405-412 라인)

2022-03-28 02:01 UTC, FrancescoJo commented on server/README.adoc
> +class MockUser(val nickname: String,
이거 Formatter 적용 다시 해 주시기 바랍니다. 이렇게 될것 같아요.

```
class MockUser(
    val nickname: String,
    val profileImageUrl: String
)
```

2022-03-28 02:20 UTC, yoonho92 commented on server/README.adoc
> +class MockUser(val nickname: String,
넵 확인 후 재 리뷰 요청드리겠습니다.

2022-03-29 02:41 UTC, yoonho92 commented on server/README.adoc
> +
[source, shell script]
----
Cannot access 'Model': it is internal in 'Companion'
----
위의 내용으로 추가했습니다.

2022-03-29 03:09 UTC, FrancescoJo commented on server/README.adoc
> +
고생하셨습니다!

2022-03-29 03:09 UTC, FrancescoJo approved these changes
고생하셨습니다. LGTM

2022-03-29 03:09 UTC, merged